// Nifty 500 Companies - NSE Stock List (as of 2024-2025)
// Format: { symbol, name, sector }

const NSE_STOCKS = [
  // Energy & Oil & Gas
  { symbol: "RELIANCE", name: "Reliance Industries Ltd", sector: "Energy" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation Ltd", sector: "Energy" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Ltd", sector: "Energy" },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd", sector: "Energy" },
  { symbol: "GAIL", name: "GAIL (India) Ltd", sector: "Energy" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation Ltd", sector: "Energy" },
  { symbol: "OIL", name: "Oil India Ltd", sector: "Energy" },
  { symbol: "MGL", name: "Mahanagar Gas Ltd", sector: "Energy" },
  { symbol: "IGL", name: "Indraprastha Gas Ltd", sector: "Energy" },
  { symbol: "PETRONET", name: "Petronet LNG Ltd", sector: "Energy" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Ltd", sector: "Energy" },
  { symbol: "CASTROLIND", name: "Castrol India Ltd", sector: "Energy" },

  // Information Technology
  { symbol: "TCS", name: "Tata Consultancy Services Ltd", sector: "IT" },
  { symbol: "INFY", name: "Infosys Ltd", sector: "IT" },
  { symbol: "WIPRO", name: "Wipro Ltd", sector: "IT" },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd", sector: "IT" },
  { symbol: "TECHM", name: "Tech Mahindra Ltd", sector: "IT" },
  { symbol: "LTIM", name: "LTIMindtree Ltd", sector: "IT" },
  { symbol: "MPHASIS", name: "Mphasis Ltd", sector: "IT" },
  { symbol: "PERSISTENT", name: "Persistent Systems Ltd", sector: "IT" },
  { symbol: "COFORGE", name: "Coforge Ltd", sector: "IT" },
  { symbol: "OFSS", name: "Oracle Financial Services Software Ltd", sector: "IT" },
  { symbol: "KPITTECH", name: "KPIT Technologies Ltd", sector: "IT" },
  { symbol: "TATAELXSI", name: "Tata Elxsi Ltd", sector: "IT" },
  { symbol: "HEXAWARE", name: "Hexaware Technologies Ltd", sector: "IT" },
  { symbol: "NIIT", name: "NIIT Ltd", sector: "IT" },
  { symbol: "MASTEK", name: "Mastek Ltd", sector: "IT" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies Ltd", sector: "IT" },
  { symbol: "NEWGEN", name: "Newgen Software Technologies Ltd", sector: "IT" },
  { symbol: "CYIENT", name: "Cyient Ltd", sector: "IT" },
  { symbol: "ZENSAR", name: "Zensar Technologies Ltd", sector: "IT" },
  { symbol: "BIRLASOFT", name: "Birlasoft Ltd", sector: "IT" },
  { symbol: "SONATSOFTW", name: "Sonata Software Ltd", sector: "IT" },
  { symbol: "FSL", name: "Firstsource Solutions Ltd", sector: "IT" },

  // Banking - Private
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd", sector: "Banking" },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd", sector: "Banking" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd", sector: "Banking" },
  { symbol: "AXISBANK", name: "Axis Bank Ltd", sector: "Banking" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd", sector: "Banking" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd", sector: "Banking" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd", sector: "Banking" },
  { symbol: "FEDERALBNK", name: "Federal Bank Ltd", sector: "Banking" },
  { symbol: "RBLBANK", name: "RBL Bank Ltd", sector: "Banking" },
  { symbol: "YESBANK", name: "Yes Bank Ltd", sector: "Banking" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank Ltd", sector: "Banking" },
  { symbol: "CSBBANK", name: "CSB Bank Ltd", sector: "Banking" },
  { symbol: "DCBBANK", name: "DCB Bank Ltd", sector: "Banking" },
  { symbol: "SOUTHBANK", name: "South Indian Bank Ltd", sector: "Banking" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank Ltd", sector: "Banking" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank Ltd", sector: "Banking" },
  { symbol: "AUBANK", name: "AU Small Finance Bank Ltd", sector: "Banking" },
  { symbol: "ESAFSFB", name: "ESAF Small Finance Bank Ltd", sector: "Banking" },

  // Banking - Public
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking" },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking" },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Banking" },
  { symbol: "IOB", name: "Indian Overseas Bank", sector: "Banking" },
  { symbol: "CENTRALBK", name: "Central Bank of India", sector: "Banking" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra", sector: "Banking" },
  { symbol: "PSB", name: "Punjab & Sind Bank", sector: "Banking" },
  { symbol: "BANKINDIA", name: "Bank of India", sector: "Banking" },
  { symbol: "UCOBANK", name: "UCO Bank", sector: "Banking" },

  // Finance & NBFCs
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd", sector: "Finance" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd", sector: "Finance" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Ltd", sector: "Finance" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment and Finance Company Ltd", sector: "Finance" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Ltd", sector: "Finance" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services Ltd", sector: "Finance" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance Ltd", sector: "Finance" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Ltd", sector: "Finance" },
  { symbol: "IIFL", name: "IIFL Finance Ltd", sector: "Finance" },
  { symbol: "PNBHOUSING", name: "PNB Housing Finance Ltd", sector: "Finance" },
  { symbol: "CANFINHOME", name: "Can Fin Homes Ltd", sector: "Finance" },
  { symbol: "HOMEFIRST", name: "Home First Finance Company India Ltd", sector: "Finance" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance India Ltd", sector: "Finance" },
  { symbol: "AAVAS", name: "Aavas Financiers Ltd", sector: "Finance" },
  { symbol: "CREDITACC", name: "CreditAccess Grameen Ltd", sector: "Finance" },
  { symbol: "SPANDANA", name: "Spandana Sphoorty Financial Ltd", sector: "Finance" },
  { symbol: "FINCABLES", name: "Finolex Cables Ltd", sector: "Finance" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance Ltd", sector: "Finance" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital Ltd", sector: "Finance" },
  { symbol: "JMFINANCIL", name: "JM Financial Ltd", sector: "Finance" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial Services Ltd", sector: "Finance" },
  { symbol: "ANGELONE", name: "Angel One Ltd", sector: "Finance" },
  { symbol: "5PAISA", name: "5Paisa Capital Ltd", sector: "Finance" },

  // Insurance
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company Ltd", sector: "Insurance" },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company Ltd", sector: "Insurance" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance Company Ltd", sector: "Insurance" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance Company Ltd", sector: "Insurance" },
  { symbol: "SBICARD", name: "SBI Cards and Payment Services Ltd", sector: "Finance" },
  { symbol: "POLICYBZR", name: "PB Fintech Ltd (Policybazaar)", sector: "Insurance" },
  { symbol: "GICRE", name: "General Insurance Corporation of India", sector: "Insurance" },
  { symbol: "NIACL", name: "New India Assurance Company Ltd", sector: "Insurance" },
  { symbol: "STARHEALTH", name: "Star Health and Allied Insurance Company Ltd", sector: "Insurance" },
  { symbol: "GODIGIT", name: "Go Digit General Insurance Ltd", sector: "Insurance" },

  // FMCG & Consumer
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd", sector: "FMCG" },
  { symbol: "ITC", name: "ITC Ltd", sector: "FMCG" },
  { symbol: "NESTLEIND", name: "Nestle India Ltd", sector: "FMCG" },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd", sector: "FMCG" },
  { symbol: "DABUR", name: "Dabur India Ltd", sector: "FMCG" },
  { symbol: "MARICO", name: "Marico Ltd", sector: "FMCG" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Ltd", sector: "FMCG" },
  { symbol: "COLPAL", name: "Colgate-Palmolive (India) Ltd", sector: "FMCG" },
  { symbol: "EMAMILTD", name: "Emami Ltd", sector: "FMCG" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd", sector: "FMCG" },
  { symbol: "PGHH", name: "Procter & Gamble Hygiene and Health Care Ltd", sector: "FMCG" },
  { symbol: "GILLETTE", name: "Gillette India Ltd", sector: "FMCG" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs Ltd", sector: "FMCG" },
  { symbol: "BAJAJCON", name: "Bajaj Consumer Care Ltd", sector: "FMCG" },
  { symbol: "MCCORMICK", name: "McCormick & Company India Ltd", sector: "FMCG" },
  { symbol: "HONASA", name: "Honasa Consumer Ltd (Mamaearth)", sector: "FMCG" },
  { symbol: "VBL", name: "Varun Beverages Ltd", sector: "FMCG" },
  { symbol: "RADICO", name: "Radico Khaitan Ltd", sector: "FMCG" },
  { symbol: "MCDOWELL-N", name: "United Spirits Ltd", sector: "FMCG" },
  { symbol: "UBL", name: "United Breweries Ltd", sector: "FMCG" },

  // Pharmaceuticals & Healthcare
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Ltd", sector: "Pharma" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Ltd", sector: "Pharma" },
  { symbol: "CIPLA", name: "Cipla Ltd", sector: "Pharma" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd", sector: "Pharma" },
  { symbol: "BIOCON", name: "Biocon Ltd", sector: "Pharma" },
  { symbol: "LUPIN", name: "Lupin Ltd", sector: "Pharma" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Ltd", sector: "Pharma" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd", sector: "Pharma" },
  { symbol: "ALKEM", name: "Alkem Laboratories Ltd", sector: "Pharma" },
  { symbol: "ABBOTINDIA", name: "Abbott India Ltd", sector: "Pharma" },
  { symbol: "PFIZER", name: "Pfizer Ltd", sector: "Pharma" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharmaceuticals Ltd", sector: "Pharma" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Ltd", sector: "Pharma" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Ltd", sector: "Pharma" },
  { symbol: "IPCALAB", name: "IPCA Laboratories Ltd", sector: "Pharma" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma Ltd", sector: "Pharma" },
  { symbol: "NATCOPHARMA", name: "Natco Pharma Ltd", sector: "Pharma" },
  { symbol: "GRANULES", name: "Granules India Ltd", sector: "Pharma" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Ltd", sector: "Healthcare" },
  { symbol: "FORTIS", name: "Fortis Healthcare Ltd", sector: "Healthcare" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute Ltd", sector: "Healthcare" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Ltd", sector: "Healthcare" },
  { symbol: "LALPATHLAB", name: "Dr. Lal PathLabs Ltd", sector: "Healthcare" },
  { symbol: "KRSNAA", name: "Krsnaa Diagnostics Ltd", sector: "Healthcare" },
  { symbol: "THYROCARE", name: "Thyrocare Technologies Ltd", sector: "Healthcare" },
  { symbol: "MEDANTA", name: "Global Health Ltd (Medanta)", sector: "Healthcare" },
  { symbol: "YATHARTH", name: "Yatharth Hospital & Trauma Care Services Ltd", sector: "Healthcare" },

  // Automobiles
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd", sector: "Auto" },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd", sector: "Auto" },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd", sector: "Auto" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd", sector: "Auto" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd", sector: "Auto" },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd", sector: "Auto" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Ltd", sector: "Auto" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd", sector: "Auto" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International Ltd", sector: "Auto" },
  { symbol: "BOSCHLTD", name: "Bosch Ltd", sector: "Auto" },
  { symbol: "EXIDEIND", name: "Exide Industries Ltd", sector: "Auto" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy & Mobility Ltd", sector: "Auto" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Ltd", sector: "Auto" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Ltd", sector: "Auto" },
  { symbol: "MRF", name: "MRF Ltd", sector: "Auto" },
  { symbol: "CEATLTD", name: "CEAT Ltd", sector: "Auto" },
  { symbol: "FORCEMOT", name: "Force Motors Ltd", sector: "Auto" },
  { symbol: "ESCORTS", name: "Escorts Kubota Ltd", sector: "Auto" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings Ltd", sector: "Auto" },
  { symbol: "UNO MINDA", name: "Uno Minda Ltd", sector: "Auto" },
  { symbol: "UNOMINDA", name: "Uno Minda Ltd", sector: "Auto" },
  { symbol: "VARROC", name: "Varroc Engineering Ltd", sector: "Auto" },
  { symbol: "OLECTRA", name: "Olectra Greentech Ltd", sector: "Auto" },
  { symbol: "SUPRAJIT", name: "Suprajit Engineering Ltd", sector: "Auto" },
  { symbol: "STARKENGG", name: "Stark Industries Ltd", sector: "Auto" },
  { symbol: "MINDAIND", name: "Minda Industries Ltd", sector: "Auto" },
  { symbol: "SUNDRMFAST", name: "Sundram Fasteners Ltd", sector: "Auto" },
  { symbol: "TIINDIA", name: "Tube Investments of India Ltd", sector: "Auto" },

  // Metals & Mining
  { symbol: "TATASTEEL", name: "Tata Steel Ltd", sector: "Metals" },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd", sector: "Metals" },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd", sector: "Metals" },
  { symbol: "VEDL", name: "Vedanta Ltd", sector: "Metals" },
  { symbol: "NMDC", name: "NMDC Ltd", sector: "Metals" },
  { symbol: "SAIL", name: "Steel Authority of India Ltd", sector: "Metals" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Ltd", sector: "Metals" },
  { symbol: "NATIONALUM", name: "National Aluminium Company Ltd", sector: "Metals" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Ltd", sector: "Metals" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Ltd", sector: "Metals" },
  { symbol: "WELSPUNLIV", name: "Welspun Living Ltd", sector: "Metals" },
  { symbol: "RATNAMANI", name: "Ratnamani Metals & Tubes Ltd", sector: "Metals" },
  { symbol: "COALINDIA", name: "Coal India Ltd", sector: "Metals" },
  { symbol: "MOIL", name: "MOIL Ltd", sector: "Metals" },
  { symbol: "GMRP&UI", name: "GMR Power and Urban Infra Ltd", sector: "Metals" },
  { symbol: "JSWENERGY", name: "JSW Energy Ltd", sector: "Energy" },
  { symbol: "JSPL", name: "Jindal Steel & Power Ltd", sector: "Metals" },
  { symbol: "SHYAMMETL", name: "Shyam Metalics and Energy Ltd", sector: "Metals" },

  // Power & Utilities
  { symbol: "NTPC", name: "NTPC Ltd", sector: "Power" },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India Ltd", sector: "Power" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd", sector: "Power" },
  { symbol: "ADANITRANS", name: "Adani Transmission Ltd", sector: "Power" },
  { symbol: "ADANIPOWER", name: "Adani Power Ltd", sector: "Power" },
  { symbol: "PFC", name: "Power Finance Corporation Ltd", sector: "Power" },
  { symbol: "REC", name: "REC Ltd", sector: "Power" },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation Ltd", sector: "Finance" },
  { symbol: "HUDCO", name: "Housing and Urban Development Corporation Ltd", sector: "Finance" },
  { symbol: "NHPC", name: "NHPC Ltd", sector: "Power" },
  { symbol: "TORNTPOWER", name: "Torrent Power Ltd", sector: "Power" },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd", sector: "Power" },
  { symbol: "CESC", name: "CESC Ltd", sector: "Power" },
  { symbol: "KPCL", name: "Karnataka Power Corporation Ltd", sector: "Power" },
  { symbol: "SJVN", name: "SJVN Ltd", sector: "Power" },
  { symbol: "THERMAX", name: "Thermax Ltd", sector: "Power" },
  { symbol: "GEPIL", name: "GE Power India Ltd", sector: "Power" },
  { symbol: "INOXWIND", name: "Inox Wind Ltd", sector: "Power" },
  { symbol: "SUZLON", name: "Suzlon Energy Ltd", sector: "Power" },
  { symbol: "PCBL", name: "PCBL Ltd", sector: "Power" },

  // Infrastructure & Construction
  { symbol: "LT", name: "Larsen & Toubro Ltd", sector: "Infrastructure" },
  { symbol: "ADANIPORTS", name: "Adani Ports and Special Economic Zone Ltd", sector: "Infrastructure" },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd", sector: "Infrastructure" },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure Ltd", sector: "Infrastructure" },
  { symbol: "IRB", name: "IRB Infrastructure Developers Ltd", sector: "Infrastructure" },
  { symbol: "KNR", name: "KNR Constructions Ltd", sector: "Infrastructure" },
  { symbol: "NCC", name: "NCC Ltd", sector: "Infrastructure" },
  { symbol: "NBCC", name: "NBCC (India) Ltd", sector: "Infrastructure" },
  { symbol: "HCC", name: "Hindustan Construction Company Ltd", sector: "Infrastructure" },
  { symbol: "PNCINFRA", name: "PNC Infratech Ltd", sector: "Infrastructure" },
  { symbol: "SADBHAV", name: "Sadbhav Engineering Ltd", sector: "Infrastructure" },
  { symbol: "AHLUCONT", name: "Ahluwalia Contracts (India) Ltd", sector: "Infrastructure" },
  { symbol: "CAPACITE", name: "Capacite Infraprojects Ltd", sector: "Infrastructure" },
  { symbol: "RITES", name: "RITES Ltd", sector: "Infrastructure" },
  { symbol: "IRCON", name: "Ircon International Ltd", sector: "Infrastructure" },
  { symbol: "RAILTEL", name: "RailTel Corporation of India Ltd", sector: "Infrastructure" },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd", sector: "Infrastructure" },
  { symbol: "TITAGARH", name: "Titagarh Rail Systems Ltd", sector: "Infrastructure" },
  { symbol: "TEXRAIL", name: "Texmaco Rail & Engineering Ltd", sector: "Infrastructure" },

  // Telecom
  { symbol: "BHARTIARTL", name: "Bharti Airtel Ltd", sector: "Telecom" },
  { symbol: "INDUSTOWER", name: "Indus Towers Ltd", sector: "Telecom" },
  { symbol: "MTNL", name: "Mahanagar Telephone Nigam Ltd", sector: "Telecom" },
  { symbol: "TATACOMM", name: "Tata Communications Ltd", sector: "Telecom" },
  { symbol: "HFCL", name: "HFCL Ltd", sector: "Telecom" },
  { symbol: "STLTECH", name: "Sterlite Technologies Ltd", sector: "Telecom" },
  { symbol: "TEJAS", name: "Tejas Networks Ltd", sector: "Telecom" },

  // Cement
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd", sector: "Cement" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd", sector: "Cement" },
  { symbol: "ACC", name: "ACC Ltd", sector: "Cement" },
  { symbol: "SHREECEM", name: "Shree Cement Ltd", sector: "Cement" },
  { symbol: "DALMIABHA", name: "Dalmia Bharat Ltd", sector: "Cement" },
  { symbol: "JKCEMENT", name: "JK Cement Ltd", sector: "Cement" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements Ltd", sector: "Cement" },
  { symbol: "HEIDELBERG", name: "HeidelbergCement India Ltd", sector: "Cement" },
  { symbol: "BIRLACORPN", name: "Birla Corporation Ltd", sector: "Cement" },
  { symbol: "NUVOCO", name: "Nuvoco Vistas Corporation Ltd", sector: "Cement" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement Ltd", sector: "Cement" },
  { symbol: "STARCEMENT", name: "Star Cement Ltd", sector: "Cement" },
  { symbol: "SANGHIBANK", name: "Sanghi Industries Ltd", sector: "Cement" },

  // Paints & Chemicals
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd", sector: "Paints" },
  { symbol: "BERGEPAINT", name: "Berger Paints India Ltd", sector: "Paints" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints Ltd", sector: "Paints" },
  { symbol: "INDIGO", name: "IndiGo (InterGlobe Aviation Ltd)", sector: "Aviation" },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd", sector: "Chemicals" },
  { symbol: "SRF", name: "SRF Ltd", sector: "Chemicals" },
  { symbol: "AARTI", name: "Aarti Industries Ltd", sector: "Chemicals" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilisers and Petrochemicals Corporation Ltd", sector: "Chemicals" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Ltd", sector: "Chemicals" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International Ltd", sector: "Chemicals" },
  { symbol: "ALKYLAMINE", name: "Alkyl Amines Chemicals Ltd", sector: "Chemicals" },
  { symbol: "FINEORG", name: "Fine Organic Industries Ltd", sector: "Chemicals" },
  { symbol: "CLEAN", name: "Clean Science and Technology Ltd", sector: "Chemicals" },
  { symbol: "ROSSARI", name: "Rossari Biotech Ltd", sector: "Chemicals" },
  { symbol: "TATACHEM", name: "Tata Chemicals Ltd", sector: "Chemicals" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers and Chemicals Ltd", sector: "Chemicals" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers & Chemicals Ltd", sector: "Chemicals" },
  { symbol: "COROMANDEL", name: "Coromandel International Ltd", sector: "Chemicals" },
  { symbol: "NFL", name: "National Fertilizers Ltd", sector: "Chemicals" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers and Chemicals Ltd", sector: "Chemicals" },
  { symbol: "SOLAR", name: "Solar Industries India Ltd", sector: "Chemicals" },
  { symbol: "BALCHEMLTD", name: "Balaji Amines Ltd", sector: "Chemicals" },

  // Capital Goods & Engineering
  { symbol: "SIEMENS", name: "Siemens Ltd", sector: "Capital Goods" },
  { symbol: "ABB", name: "ABB India Ltd", sector: "Capital Goods" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd", sector: "Capital Goods" },
  { symbol: "CUMMINSIND", name: "Cummins India Ltd", sector: "Capital Goods" },
  { symbol: "HAVELLS", name: "Havells India Ltd", sector: "Capital Goods" },
  { symbol: "VOLTAS", name: "Voltas Ltd", sector: "Capital Goods" },
  { symbol: "BLUESTARCO", name: "Blue Star Ltd", sector: "Capital Goods" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India Ltd", sector: "Capital Goods" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals Ltd", sector: "Capital Goods" },
  { symbol: "ORIENTELEC", name: "Orient Electric Ltd", sector: "Capital Goods" },
  { symbol: "POLYCAB", name: "Polycab India Ltd", sector: "Capital Goods" },
  { symbol: "KEI", name: "KEI Industries Ltd", sector: "Capital Goods" },
  { symbol: "SKFINDIA", name: "SKF India Ltd", sector: "Capital Goods" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India Ltd", sector: "Capital Goods" },
  { symbol: "TIMKEN", name: "Timken India Ltd", sector: "Capital Goods" },
  { symbol: "GRINDWELL", name: "Grindwell Norton Ltd", sector: "Capital Goods" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments Ltd", sector: "Capital Goods" },
  { symbol: "KIRLOSENG", name: "Kirloskar Brothers Ltd", sector: "Capital Goods" },
  { symbol: "KIRLFER", name: "Kirloskar Ferrous Industries Ltd", sector: "Capital Goods" },
  { symbol: "TRITURBINE", name: "Triveni Turbine Ltd", sector: "Capital Goods" },
  { symbol: "AIAENG", name: "AIA Engineering Ltd", sector: "Capital Goods" },
  { symbol: "CARBORUNIV", name: "Carborundum Universal Ltd", sector: "Capital Goods" },
  { symbol: "CG", name: "CG Power and Industrial Solutions Ltd", sector: "Capital Goods" },
  { symbol: "CGPOWER", name: "CG Power and Industrial Solutions Ltd", sector: "Capital Goods" },
  { symbol: "BEL", name: "Bharat Electronics Ltd", sector: "Capital Goods" },
  { symbol: "HAL", name: "Hindustan Aeronautics Ltd", sector: "Capital Goods" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard Ltd", sector: "Capital Goods" },
  { symbol: "MAZAGON", name: "Mazagon Dock Shipbuilders Ltd", sector: "Capital Goods" },
  { symbol: "BEML", name: "BEML Ltd", sector: "Capital Goods" },
  { symbol: "HBLPOWER", name: "HBL Power Systems Ltd", sector: "Capital Goods" },

  // Consumer Durables & Electronics
  { symbol: "TITAN", name: "Titan Company Ltd", sector: "Consumer Durables" },
  { symbol: "VGUARD", name: "V-Guard Industries Ltd", sector: "Consumer Durables" },
  { symbol: "RAJESHEXPO", name: "Rajesh Exports Ltd", sector: "Consumer Durables" },
  { symbol: "BATAINDIA", name: "Bata India Ltd", sector: "Consumer Durables" },
  { symbol: "RELAXO", name: "Relaxo Footwears Ltd", sector: "Consumer Durables" },
  { symbol: "VIP", name: "V.I.P. Industries Ltd", sector: "Consumer Durables" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods India Ltd", sector: "Consumer Durables" },

  // Retail & E-Commerce
  { symbol: "DMART", name: "Avenue Supermarts Ltd (D-Mart)", sector: "Retail" },
  { symbol: "TRENT", name: "Trent Ltd", sector: "Retail" },
  { symbol: "SHOPERSTOP", name: "Shoppers Stop Ltd", sector: "Retail" },
  { symbol: "VMART", name: "V-Mart Retail Ltd", sector: "Retail" },
  { symbol: "ZOMATO", name: "Zomato Ltd", sector: "Consumer Tech" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures Ltd (Nykaa)", sector: "Consumer Tech" },
  { symbol: "PAYTM", name: "One97 Communications Ltd (Paytm)", sector: "Consumer Tech" },
  { symbol: "NAUKRI", name: "Info Edge (India) Ltd", sector: "Consumer Tech" },
  { symbol: "IRCTC", name: "Indian Railway Catering and Tourism Corporation Ltd", sector: "Consumer Tech" },
  { symbol: "CARTRADE", name: "CarTrade Tech Ltd", sector: "Consumer Tech" },
  { symbol: "EASY TRIP", name: "Easy Trip Planners Ltd", sector: "Consumer Tech" },
  { symbol: "EASEMYTRIP", name: "Easy Trip Planners Ltd", sector: "Consumer Tech" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies Ltd", sector: "Consumer Tech" },
  { symbol: "JUSTDIAL", name: "Just Dial Ltd", sector: "Consumer Tech" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH Ltd", sector: "Consumer Tech" },
  { symbol: "TEAMLEASE", name: "TeamLease Services Ltd", sector: "Consumer Tech" },
  { symbol: "QUESS", name: "Quess Corp Ltd", sector: "Consumer Tech" },

  // Aviation & Logistics
  { symbol: "SPICEJET", name: "SpiceJet Ltd", sector: "Aviation" },
  { symbol: "AIRINDIA", name: "Air India Ltd", sector: "Aviation" },
  { symbol: "BLUEDART", name: "Blue Dart Express Ltd", sector: "Logistics" },
  { symbol: "DELHIVERY", name: "Delhivery Ltd", sector: "Logistics" },
  { symbol: "MAHLOG", name: "Mahindra Logistics Ltd", sector: "Logistics" },
  { symbol: "GICRE", name: "General Insurance Corporation of India", sector: "Insurance" },
  { symbol: "CONCOR", name: "Container Corporation of India Ltd", sector: "Logistics" },
  { symbol: "ALLCARGO", name: "Allcargo Logistics Ltd", sector: "Logistics" },
  { symbol: "GATEWAY", name: "Gateway Distriparks Ltd", sector: "Logistics" },
  { symbol: "TCI", name: "Transport Corporation of India Ltd", sector: "Logistics" },

  // Real Estate
  { symbol: "DLF", name: "DLF Ltd", sector: "Real Estate" },
  { symbol: "GODREJPROP", name: "Godrej Properties Ltd", sector: "Real Estate" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Ltd", sector: "Real Estate" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects Ltd", sector: "Real Estate" },
  { symbol: "BRIGADE", name: "Brigade Enterprises Ltd", sector: "Real Estate" },
  { symbol: "PHOENIXLTD", name: "The Phoenix Mills Ltd", sector: "Real Estate" },
  { symbol: "KOLTEPATIL", name: "Kolte-Patil Developers Ltd", sector: "Real Estate" },
  { symbol: "SOBHA", name: "Sobha Ltd", sector: "Real Estate" },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace Developers Ltd", sector: "Real Estate" },
  { symbol: "SUNTECK", name: "Sunteck Realty Ltd", sector: "Real Estate" },
  { symbol: "INDIABULLS", name: "Indiabulls Real Estate Ltd", sector: "Real Estate" },
  { symbol: "NESCO", name: "NESCO Ltd", sector: "Real Estate" },
  { symbol: "EMBASSY", name: "Embassy Office Parks REIT", sector: "Real Estate" },
  { symbol: "MINDSPACE", name: "Mindspace Business Parks REIT", sector: "Real Estate" },

  // Textile & Apparel
  { symbol: "PAGEIND", name: "Page Industries Ltd", sector: "Textile" },
  { symbol: "RAYMOND", name: "Raymond Ltd", sector: "Textile" },
  { symbol: "ARVIND", name: "Arvind Ltd", sector: "Textile" },
  { symbol: "TRIDENT", name: "Trident Ltd", sector: "Textile" },
  { symbol: "WELSPUNIND", name: "Welspun India Ltd", sector: "Textile" },
  { symbol: "VARDHMAN", name: "Vardhman Textiles Ltd", sector: "Textile" },
  { symbol: "SIYARAM", name: "Siyaram Silk Mills Ltd", sector: "Textile" },
  { symbol: "DONEAR", name: "Donear Industries Ltd", sector: "Textile" },
  { symbol: "KPR", name: "KPR Mill Ltd", sector: "Textile" },
  { symbol: "FILATEX", name: "Filatex India Ltd", sector: "Textile" },

  // Specialty Chemicals & Agrochemicals
  { symbol: "PI", name: "PI Industries Ltd", sector: "Agrochemicals" },
  { symbol: "BAYER", name: "Bayer CropScience Ltd", sector: "Agrochemicals" },
  { symbol: "RALLIS", name: "Rallis India Ltd", sector: "Agrochemicals" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India Ltd", sector: "Agrochemicals" },
  { symbol: "DHANUKA", name: "Dhanuka Agritech Ltd", sector: "Agrochemicals" },
  { symbol: "CORTEVA", name: "Corteva Agriscience India Ltd", sector: "Agrochemicals" },
  { symbol: "UPL", name: "UPL Ltd", sector: "Agrochemicals" },
  { symbol: "INSECTICID", name: "Insecticides (India) Ltd", sector: "Agrochemicals" },

  // Packaging
  { symbol: "UFLEX", name: "UFLEX Ltd", sector: "Packaging" },
  { symbol: "MOLD-TEK", name: "Mold-Tek Packaging Ltd", sector: "Packaging" },
  { symbol: "HUHTAMAKI", name: "Huhtamaki India Ltd", sector: "Packaging" },
  { symbol: "MANJUSHREE", name: "Manjushree Technopack Ltd", sector: "Packaging" },

  // Gems & Jewellery
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India Ltd", sector: "Jewellery" },
  { symbol: "SENCO", name: "Senco Gold Ltd", sector: "Jewellery" },
  { symbol: "THANGAMAYIL", name: "Thangamayil Jewellery Ltd", sector: "Jewellery" },
  { symbol: "PCJEWELLER", name: "PC Jeweller Ltd", sector: "Jewellery" },

  // Media & Entertainment
  { symbol: "SUNTV", name: "Sun TV Network Ltd", sector: "Media" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises Ltd", sector: "Media" },
  { symbol: "NETWORK18", name: "Network18 Media & Investments Ltd", sector: "Media" },
  { symbol: "TV18BRDCST", name: "TV18 Broadcast Ltd", sector: "Media" },
  { symbol: "DISHTV", name: "Dish TV India Ltd", sector: "Media" },
  { symbol: "SAREGAMA", name: "Saregama India Ltd", sector: "Media" },
  { symbol: "NAZARA", name: "Nazara Technologies Ltd", sector: "Media" },
  { symbol: "TIPS", name: "Tips Industries Ltd", sector: "Media" },

  // Diversified / Conglomerate
  { symbol: "GODREJIND", name: "Godrej Industries Ltd", sector: "Diversified" },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation Ltd", sector: "Diversified" },
  { symbol: "3MINDIA", name: "3M India Ltd", sector: "Diversified" },
  { symbol: "HONAUT", name: "Honeywell Automation India Ltd", sector: "Diversified" },
  { symbol: "GILLETTE", name: "Gillette India Ltd", sector: "FMCG" },

  // Education
  { symbol: "NAVNETEDUL", name: "Navneet Education Ltd", sector: "Education" },
  { symbol: "CAREERPOINT", name: "Career Point Ltd", sector: "Education" },
  { symbol: "MTL", name: "MT Educare Ltd", sector: "Education" },
  { symbol: "VERITAAS", name: "Veritaas Advertising Ltd", sector: "Education" },

  // Hotels & Tourism
  { symbol: "INDHOTEL", name: "The Indian Hotels Company Ltd (Taj Hotels)", sector: "Hotels" },
  { symbol: "EIHOTEL", name: "EIH Ltd (Oberoi Hotels)", sector: "Hotels" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels Ltd", sector: "Hotels" },
  { symbol: "CHALET", name: "Chalet Hotels Ltd", sector: "Hotels" },
  { symbol: "MAHINDHOLIDAY", name: "Mahindra Holidays & Resorts India Ltd", sector: "Hotels" },

  // Paper & Printing
  { symbol: "ITC", name: "ITC Ltd", sector: "FMCG" },
  { symbol: "JKPAPER", name: "JK Paper Ltd", sector: "Paper" },
  { symbol: "TNPL", name: "Tamil Nadu Newsprint and Papers Ltd", sector: "Paper" },
  { symbol: "ANDPAPER", name: "West Coast Paper Mills Ltd", sector: "Paper" },
  { symbol: "CENTURYTEX", name: "Century Textiles and Industries Ltd", sector: "Paper" },

  // Sugar
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Ltd", sector: "Sugar" },
  { symbol: "BAJAJHIND", name: "Bajaj Hindusthan Sugar Ltd", sector: "Sugar" },
  { symbol: "TRIVENI", name: "Triveni Engineering & Industries Ltd", sector: "Sugar" },
  { symbol: "RENUKA", name: "Shree Renuka Sugars Ltd", sector: "Sugar" },

  // Diversified Financial Services & Exchanges
  { symbol: "BSE", name: "BSE Ltd", sector: "Finance" },
  { symbol: "CDSL", name: "Central Depository Services (India) Ltd", sector: "Finance" },
  { symbol: "CAMS", name: "Computer Age Management Services Ltd", sector: "Finance" },
  { symbol: "KFINTECH", name: "KFin Technologies Ltd", sector: "Finance" },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd", sector: "Banking" },
  { symbol: "MCX", name: "Multi Commodity Exchange of India Ltd", sector: "Finance" },
  { symbol: "NSDL", name: "National Securities Depository Ltd", sector: "Finance" },

  // Additional Pharma / Biotech
  { symbol: "SUVEN", name: "Suven Pharmaceuticals Ltd", sector: "Pharma" },
  { symbol: "LAURUS", name: "Laurus Labs Ltd", sector: "Pharma" },
  { symbol: "STRIDES", name: "Strides Pharma Science Ltd", sector: "Pharma" },
  { symbol: "ERIS", name: "Eris Lifesciences Ltd", sector: "Pharma" },
  { symbol: "JB", name: "J.B. Chemicals & Pharmaceuticals Ltd", sector: "Pharma" },
  { symbol: "JBCHEPHARM", name: "J.B. Chemicals & Pharmaceuticals Ltd", sector: "Pharma" },
  { symbol: "LAURUSLABS", name: "Laurus Labs Ltd", sector: "Pharma" },
  { symbol: "SMSPHARMA", name: "SMS Pharmaceuticals Ltd", sector: "Pharma" },
  { symbol: "SOLARA", name: "Solara Active Pharma Sciences Ltd", sector: "Pharma" },
  { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories Ltd", sector: "Pharma" },
  { symbol: "SHILPAMED", name: "Shilpa Medicare Ltd", sector: "Pharma" },

  // Cables & Wires
  { symbol: "POLYCAB", name: "Polycab India Ltd", sector: "Capital Goods" },
  { symbol: "FINOLEX", name: "Finolex Cables Ltd", sector: "Capital Goods" },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd", sector: "Infrastructure" },

  // Footwear
  { symbol: "CAMPUS", name: "Campus Activewear Ltd", sector: "Consumer Durables" },
  { symbol: "MIRZA", name: "Mirza International Ltd", sector: "Consumer Durables" },

  // Food Processing
  { symbol: "GODREJAGRO", name: "Godrej Agrovet Ltd", sector: "FMCG" },
  { symbol: "VENKEYS", name: "Venkateshwara Hatcheries Ltd", sector: "FMCG" },
  { symbol: "HATSUN", name: "Hatsun Agro Product Ltd", sector: "FMCG" },
  { symbol: "HERITAGE", name: "Heritage Foods Ltd", sector: "FMCG" },
  { symbol: "PARAS", name: "Paras Defence and Space Technologies Ltd", sector: "Defence" },

  // Defence
  { symbol: "HAL", name: "Hindustan Aeronautics Ltd", sector: "Defence" },
  { symbol: "BEL", name: "Bharat Electronics Ltd", sector: "Defence" },
  { symbol: "BDL", name: "Bharat Dynamics Ltd", sector: "Defence" },
  { symbol: "BEML", name: "BEML Ltd", sector: "Defence" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders & Engineers Ltd", sector: "Defence" },
  { symbol: "MIDHANI", name: "Mishra Dhatu Nigam Ltd", sector: "Defence" },
  { symbol: "ASTRA", name: "Astra Microwave Products Ltd", sector: "Defence" },
  { symbol: "DATAPATTNS", name: "Data Patterns (India) Ltd", sector: "Defence" },

  // Renewable Energy
  { symbol: "WAAREE", name: "Waaree Energies Ltd", sector: "Renewable Energy" },
  { symbol: "PREMIER", name: "Premier Energies Ltd", sector: "Renewable Energy" },
  { symbol: "WEBSOL", name: "Websol Energy System Ltd", sector: "Renewable Energy" },
  { symbol: "BOROSCI", name: "Borosil Renewables Ltd", sector: "Renewable Energy" },
  { symbol: "SOLARINDS", name: "Solar Industries India Ltd", sector: "Renewable Energy" },

  // Semiconductor & Electronics Manufacturing
  { symbol: "TATAELXSI", name: "Tata Elxsi Ltd", sector: "IT" },
  { symbol: "DIXON", name: "Dixon Technologies (India) Ltd", sector: "Electronics" },
  { symbol: "AMBER", name: "Amber Enterprises India Ltd", sector: "Electronics" },
  { symbol: "SYRMA", name: "Syrma SGS Technology Ltd", sector: "Electronics" },
  { symbol: "KAYNES", name: "Kaynes Technology India Ltd", sector: "Electronics" },
  { symbol: "PGEL", name: "PG Electroplast Ltd", sector: "Electronics" },
  { symbol: "ELIN", name: "Elin Electronics Ltd", sector: "Electronics" },

  // Additional Large Caps & Mid Caps
  { symbol: "MFSL", name: "Max Financial Services Ltd", sector: "Insurance" },
  { symbol: "LTTS", name: "L&T Technology Services Ltd", sector: "IT" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies Ltd", sector: "IT" },
  { symbol: "TANLA", name: "Tanla Platforms Ltd", sector: "IT" },
  { symbol: "INTELLECT", name: "Intellect Design Arena Ltd", sector: "IT" },
  { symbol: "ROUTE", name: "Route Mobile Ltd", sector: "IT" },
  { symbol: "SUBEXLTD", name: "Subex Ltd", sector: "IT" },
  { symbol: "TATATECH", name: "Tata Technologies Ltd", sector: "IT" },
  { symbol: "BSOFT", name: "BSOFT Ltd", sector: "IT" },
  { symbol: "NIITMTS", name: "NIIT Learning Systems Ltd", sector: "IT" },
  { symbol: "RAMCOSYS", name: "Ramco Systems Ltd", sector: "IT" },
  { symbol: "SAKSOFT", name: "Saksoft Ltd", sector: "IT" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies Ltd", sector: "IT" },

  // Miscellaneous / Others
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals Ltd", sector: "Capital Goods" },
  { symbol: "SYMPHONY", name: "Symphony Ltd", sector: "Capital Goods" },
  { symbol: "IFBIND", name: "IFB Industries Ltd", sector: "Capital Goods" },
  { symbol: "PRINCEPIPE", name: "Prince Pipes and Fittings Ltd", sector: "Capital Goods" },
  { symbol: "ASTRAL", name: "Astral Ltd", sector: "Capital Goods" },
  { symbol: "FINOLEX", name: "Finolex Industries Ltd", sector: "Capital Goods" },
  { symbol: "SUPREMEIND", name: "Supreme Industries Ltd", sector: "Capital Goods" },
  { symbol: "APOLLOPIPE", name: "Apollo Pipes Ltd", sector: "Capital Goods" },
  { symbol: "EPIGRAL", name: "Epigral Ltd", sector: "Chemicals" },
  { symbol: "VINATIORGA", name: "Vinati Organics Ltd", sector: "Chemicals" },
  { symbol: "NOCIL", name: "NOCIL Ltd", sector: "Chemicals" },
  { symbol: "GALAXYSURF", name: "Galaxy Surfactants Ltd", sector: "Chemicals" },
  { symbol: "TATVA", name: "Tatva Chintan Pharma Chem Ltd", sector: "Chemicals" },
  { symbol: "ANUPAM", name: "Anupam Rasayan India Ltd", sector: "Chemicals" },
  { symbol: "IGPL", name: "IG Petrochemicals Ltd", sector: "Chemicals" },
  { symbol: "CHEMBOND", name: "Chembond Chemicals Ltd", sector: "Chemicals" },
  { symbol: "HARIOMPIPE", name: "Hariom Pipe Industries Ltd", sector: "Metals" },
  { symbol: "MSTCLTD", name: "MSTC Ltd", sector: "Metals" },
  { symbol: "TINPLATE", name: "Tinplate Company of India Ltd", sector: "Metals" },
  { symbol: "WELCORP", name: "Welspun Corp Ltd", sector: "Metals" },
  { symbol: "RAMASTEEL", name: "Rama Steel Tubes Ltd", sector: "Metals" },
  { symbol: "KALYANI", name: "Kalyani Steel Ltd", sector: "Metals" },
  { symbol: "ISMT", name: "ISMT Ltd", sector: "Metals" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics Ltd", sector: "Building Materials" },
  { symbol: "CERA", name: "Cera Sanitaryware Ltd", sector: "Building Materials" },
  { symbol: "SOMANY", name: "Somany Ceramics Ltd", sector: "Building Materials" },
  { symbol: "ORIENTCER", name: "Orient Bell Ltd", sector: "Building Materials" },
  { symbol: "VETO", name: "Veto Switchgears and Cables Ltd", sector: "Building Materials" },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd", sector: "Chemicals" },
  { symbol: "CENTURYPLY", name: "Century Plyboards (India) Ltd", sector: "Building Materials" },
  { symbol: "GREENPLY", name: "Greenply Industries Ltd", sector: "Building Materials" },
  { symbol: "GREENPANEL", name: "Greenpanel Industries Ltd", sector: "Building Materials" },
  { symbol: "SHEELA", name: "Sheela Foam Ltd", sector: "Consumer Durables" },
  { symbol: "KURL-ON", name: "Kurl-on Ltd", sector: "Consumer Durables" },
  { symbol: "DUFLUX", name: "Duflux Ltd", sector: "Consumer Durables" },
  { symbol: "HAVELLS", name: "Havells India Ltd", sector: "Capital Goods" },
  { symbol: "BAJAJELEC", name: "Bajaj Electricals Ltd", sector: "Capital Goods" },
  { symbol: "TTKPRESTIG", name: "TTK Prestige Ltd", sector: "Consumer Durables" },
  { symbol: "HAWKENCYCL", name: "Hawkins Cookers Ltd", sector: "Consumer Durables" },
  { symbol: "STOVEKRAFT", name: "Stove Kraft Ltd", sector: "Consumer Durables" },
  { symbol: "HINDWARE", name: "Hindware Home Innovation Ltd", sector: "Consumer Durables" },
  { symbol: "ORIENTBELL", name: "Orient Bell Ltd", sector: "Building Materials" },
  { symbol: "MAHSEAMLES", name: "Maharashtra Seamless Ltd", sector: "Metals" },
  { symbol: "SRPL", name: "Shree Ram Proteins Ltd", sector: "FMCG" },

  // Water Treatment & Environment
  { symbol: "VA TECH", name: "VA Tech Wabag Ltd", sector: "Infrastructure" },
  { symbol: "VATECH", name: "VA Tech Wabag Ltd", sector: "Infrastructure" },
  { symbol: "ENVIROKLEEN", name: "Environkleen Ltd", sector: "Infrastructure" },
  { symbol: "ION EXCHANGE", name: "Ion Exchange (India) Ltd", sector: "Infrastructure" },
  { symbol: "IONEXCHANG", name: "Ion Exchange (India) Ltd", sector: "Infrastructure" },

  // Agri / Plantations
  { symbol: "TATACONS", name: "Tata Consumer Products Ltd", sector: "FMCG" },
  { symbol: "CCL", name: "CCL Products (India) Ltd", sector: "FMCG" },
  { symbol: "TASTY BITE", name: "Tasty Bite Eatables Ltd", sector: "FMCG" },
  { symbol: "USHAMART", name: "Usha Martin Ltd", sector: "Metals" },
  { symbol: "ZUARI", name: "Zuari Agro Chemicals Ltd", sector: "Agrochemicals" },

  // Additional IT / Tech
  { symbol: "ECLERX", name: "eClerx Services Ltd", sector: "IT" },
  { symbol: "EXPLEO", name: "Expleo Solutions Ltd", sector: "IT" },
  { symbol: "NIITLTD", name: "NIIT Ltd", sector: "IT" },
  { symbol: "FULLIFE", name: "Fullife Healthcare Pvt Ltd", sector: "Pharma" },
  { symbol: "INDIAINFO", name: "India Infoline Ltd", sector: "Finance" },
  { symbol: "IIFLWAM", name: "IIFL Wealth Management Ltd", sector: "Finance" },
  { symbol: "360ONE", name: "360 One WAM Ltd", sector: "Finance" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management Ltd", sector: "Finance" },
  { symbol: "GEOJITFSL", name: "Geojit Financial Services Ltd", sector: "Finance" },
  { symbol: "EDELWEISS", name: "Edelweiss Financial Services Ltd", sector: "Finance" },
  { symbol: "EMKAY", name: "Emkay Global Financial Services Ltd", sector: "Finance" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank Ltd", sector: "Banking" },
  { symbol: "TMKFINANCE", name: "TMK Finance Ltd", sector: "Finance" },
  { symbol: "STARPAPER", name: "Star Paper Mills Ltd", sector: "Paper" },
  { symbol: "SSWL", name: "Steel Strips Wheels Ltd", sector: "Auto" },
  { symbol: "ENDURANCE", name: "Endurance Technologies Ltd", sector: "Auto" },
  { symbol: "SMLISUZU", name: "SML Isuzu Ltd", sector: "Auto" },
  { symbol: "ISUZU", name: "Isuzu Motors India Ltd", sector: "Auto" },
  { symbol: "MOLDTKPAC", name: "Mold-Tek Packaging Ltd", sector: "Packaging" },
  { symbol: "DODLA", name: "Dodla Dairy Ltd", sector: "FMCG" },
  { symbol: "PARAG", name: "Parag Milk Foods Ltd", sector: "FMCG" },
  { symbol: "PRAJIND", name: "Praj Industries Ltd", sector: "Capital Goods" },
  { symbol: "WALCHAND", name: "Walchandnagar Industries Ltd", sector: "Capital Goods" },
  { symbol: "SANGHVIMOV", name: "Sanghvi Movers Ltd", sector: "Infrastructure" },
  { symbol: "GESHIP", name: "The Great Eastern Shipping Company Ltd", sector: "Logistics" },
  { symbol: "SCI", name: "Shipping Corporation of India Ltd", sector: "Logistics" },
  { symbol: "ESCOIND", name: "Escorts Kubota Ltd", sector: "Auto" },
  { symbol: "VOLTAMP", name: "Voltamp Transformers Ltd", sector: "Capital Goods" },
  { symbol: "TRANSFORMRS", name: "Transformers and Rectifiers (India) Ltd", sector: "Capital Goods" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India Ltd", sector: "Capital Goods" },
  { symbol: "GE", name: "GE T&D India Ltd", sector: "Capital Goods" },
  { symbol: "INOXINDIA", name: "INOX India Ltd", sector: "Capital Goods" },
  { symbol: "TARACHAND", name: "Tara Chand International Ltd", sector: "Logistics" },
  { symbol: "IFCI", name: "IFCI Ltd", sector: "Finance" },
  { symbol: "IDBI", name: "IDBI Bank Ltd", sector: "Banking" },
  { symbol: "GMBREW", name: "G M Breweries Ltd", sector: "FMCG" },
  { symbol: "BCL", name: "BCL Industries Ltd", sector: "FMCG" },
  { symbol: "BALAJIDIST", name: "Balaji Distilleries Ltd", sector: "FMCG" },
  { symbol: "GLOBUSSPR", name: "Globus Spirits Ltd", sector: "FMCG" },
  { symbol: "TIDEWATER", name: "Tide Water Oil Co. (India) Ltd", sector: "Energy" },
  { symbol: "GOLDENTOBC", name: "Golden Tobacco Ltd", sector: "FMCG" },
  { symbol: "VST", name: "VST Industries Ltd", sector: "FMCG" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips India Ltd", sector: "FMCG" },
  { symbol: "NCLIND", name: "NCL Industries Ltd", sector: "Building Materials" },
  { symbol: "CCHLTD", name: "Creative Castings Ltd", sector: "Metals" },
  { symbol: "PRATAAP", name: "Prataap Snacks Ltd", sector: "FMCG" },
  { symbol: "DFM", name: "DFM Foods Ltd", sector: "FMCG" },
  { symbol: "BIKAJI", name: "Bikaji Foods International Ltd", sector: "FMCG" },
  { symbol: "DEVYANI", name: "Devyani International Ltd", sector: "FMCG" },
  { symbol: "WESTLIFE", name: "Westlife Foodworld Ltd", sector: "FMCG" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks Ltd", sector: "FMCG" },
  { symbol: "BARBEQUE", name: "Barbeque-Nation Hospitality Ltd", sector: "Hotels" },
  { symbol: "SPECIALITY", name: "Speciality Restaurants Ltd", sector: "Hotels" },
  { symbol: "BURGER", name: "Burger King India Ltd (Restaurant Brands Asia)", sector: "FMCG" },
  { symbol: "RBA", name: "Restaurant Brands Asia Ltd", sector: "FMCG" },
  { symbol: "JUBLPHARMA", name: "Jubilant Pharmova Ltd", sector: "Pharma" },
  { symbol: "JUBLINDS", name: "Jubilant Ingrevia Ltd", sector: "Chemicals" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd", sector: "Banking" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Ltd", sector: "Finance" },
  { symbol: "LICINDIA", name: "Life Insurance Corporation of India", sector: "Insurance" },
  { symbol: "SGBOIFINANCE", name: "SGB Financials", sector: "Finance" },
  { symbol: "ABSLAMC", name: "Aditya Birla Sun Life AMC Ltd", sector: "Finance" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management Company Ltd", sector: "Finance" },
  { symbol: "NIPPONLIFE", name: "Nippon Life India Asset Management Ltd", sector: "Finance" },
  { symbol: "UTIAMC", name: "UTI Asset Management Company Ltd", sector: "Finance" },
  { symbol: "KGAMC", name: "Kotak Mahindra Asset Management Company", sector: "Finance" },

  // More Auto Ancillaries
  { symbol: "WABCO", name: "ZF Commercial Vehicle Control Systems India Ltd", sector: "Auto" },
  { symbol: "GABRIEL", name: "Gabriel India Ltd", sector: "Auto" },
  { symbol: "MNRINDIA", name: "MNR Industries Ltd", sector: "Auto" },
  { symbol: "SHARDAMOTR", name: "Sharda Motor Industries Ltd", sector: "Auto" },
  { symbol: "LUMAXTECH", name: "Lumax Auto Technologies Ltd", sector: "Auto" },
  { symbol: "LUMAXIND", name: "Lumax Industries Ltd", sector: "Auto" },
  { symbol: "SUBROS", name: "Subros Ltd", sector: "Auto" },
  { symbol: "MOTHERMSS", name: "Minda Corporation Ltd", sector: "Auto" },
  { symbol: "MINDACORP", name: "Minda Corporation Ltd", sector: "Auto" },
  { symbol: "SANSERA", name: "Sansera Engineering Ltd", sector: "Auto" },
  { symbol: "CRAFTSMAN", name: "Craftsman Automation Ltd", sector: "Auto" },
  { symbol: "JITFINFRA", name: "JIT Finance and Infrastructure Ltd", sector: "Auto" },
  { symbol: "DYNAMATECH", name: "Dynamatic Technologies Ltd", sector: "Auto" },

  // More Infrastructure
  { symbol: "WELSPUN", name: "Welspun Enterprises Ltd", sector: "Infrastructure" },
  { symbol: "HAPPIESTMIND", name: "Happiest Minds Technologies Ltd", sector: "IT" },
  { symbol: "JMCPROJECT", name: "JMC Projects (India) Ltd", sector: "Infrastructure" },
  { symbol: "DBCORP", name: "D.B. Corp Ltd", sector: "Media" },
  { symbol: "JAGRAN", name: "Jagran Prakashan Ltd", sector: "Media" },
  { symbol: "HT MEDIA", name: "HT Media Ltd", sector: "Media" },
  { symbol: "HTMEDIA", name: "HT Media Ltd", sector: "Media" },

  // Asset Management / Wealth
  { symbol: "WEALTH", name: "Wealth First Portfolio Managers Ltd", sector: "Finance" },
  { symbol: "IIFLSEC", name: "IIFL Securities Ltd", sector: "Finance" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management Ltd", sector: "Finance" },
  { symbol: "DOLAT", name: "Dolat Investments Ltd", sector: "Finance" },

  // Miscellaneous remaining to reach 500
  { symbol: "FIEM", name: "FIEM Industries Ltd", sector: "Auto" },
  { symbol: "SETCO", name: "Setco Automotive Ltd", sector: "Auto" },
  { symbol: "JKIL", name: "J. Kumar Infraprojects Ltd", sector: "Infrastructure" },
  { symbol: "DILIPBUILD", name: "Dilip Buildcon Ltd", sector: "Infrastructure" },
  { symbol: "GAYAPROJ", name: "Gayatri Projects Ltd", sector: "Infrastructure" },
  { symbol: "HGINFRA", name: "H.G. Infra Engineering Ltd", sector: "Infrastructure" },
  { symbol: "GPPL", name: "Gujarat Pipavav Port Ltd", sector: "Infrastructure" },
  { symbol: "ESSARSHP", name: "Essar Shipping Ltd", sector: "Logistics" },
  { symbol: "WOCKPHARMA", name: "Wockhardt Ltd", sector: "Pharma" },
  { symbol: "NECTAR", name: "Nectar Lifesciences Ltd", sector: "Pharma" },
  { symbol: "HEIDEL", name: "HeidelbergCement India Ltd", sector: "Cement" },
  { symbol: "TCLCONS", name: "TCL Consulting Ltd", sector: "IT" },
  { symbol: "DBREALTY", name: "D B Realty Ltd", sector: "Real Estate" },
  { symbol: "IBREALEST", name: "Indiabulls Real Estate Ltd", sector: "Real Estate" },
  { symbol: "SQUADPHARMA", name: "Squad Pharma Ltd", sector: "Pharma" },
  { symbol: "LGBBROSLTD", name: "LGB Brothers Ltd", sector: "Capital Goods" },
  { symbol: "GHCL", name: "GHCL Ltd", sector: "Chemicals" },
  { symbol: "TGBHOTELS", name: "TGB Banquets and Hotels Ltd", sector: "Hotels" },
  { symbol: "MHRIL", name: "Mahindra Holidays & Resorts India Ltd", sector: "Hotels" },
  { symbol: "WONDERLA", name: "Wonderla Holidays Ltd", sector: "Hotels" },
  { symbol: "THOMASCOOK", name: "Thomas Cook (India) Ltd", sector: "Hotels" },
  { symbol: "COX&KINGS", name: "Cox & Kings Ltd", sector: "Hotels" },
  { symbol: "ORIENTHOT", name: "Oriental Hotels Ltd", sector: "Hotels" },
  { symbol: "TAJGVK", name: "Taj GVK Hotels & Resorts Ltd", sector: "Hotels" },
  { symbol: "ITDC", name: "India Tourism Development Corporation Ltd", sector: "Hotels" },
  { symbol: "STERLINRES", name: "Sterling & Wilson Renewable Energy Ltd", sector: "Renewable Energy" },
  { symbol: "WINDWORLD", name: "WindWorld (India) Ltd", sector: "Renewable Energy" },
  { symbol: "GREENKO", name: "Greenko Energies Private Ltd", sector: "Renewable Energy" },
  { symbol: "TORNTPOWER", name: "Torrent Power Ltd", sector: "Power" },
  { symbol: "RPOWER", name: "Reliance Power Ltd", sector: "Power" },
  { symbol: "JPPOWER", name: "Jaiprakash Power Ventures Ltd", sector: "Power" },
  { symbol: "KALPATPOWR", name: "KEC International Ltd", sector: "Infrastructure" },
  { symbol: "KEC", name: "KEC International Ltd", sector: "Infrastructure" },
  { symbol: "JYOTISTRUC", name: "Jyoti Structures Ltd", sector: "Infrastructure" },
  { symbol: "STERLITE", name: "Sterlite Power Transmission Ltd", sector: "Infrastructure" },
  { symbol: "INDIGRID", name: "IndiGrid Infrastructure Investment Trust", sector: "Infrastructure" },
  { symbol: "POWERMECH", name: "Powermech Projects Ltd", sector: "Infrastructure" },
  { symbol: "ENGINERSIN", name: "Engineers India Ltd", sector: "Infrastructure" },
  { symbol: "WABAG", name: "VA Tech Wabag Ltd", sector: "Infrastructure" },
  { symbol: "SUPR", name: "Supreme Petrochem Ltd", sector: "Chemicals" },
  { symbol: "SUVIDHAA", name: "Suvidhaa Infoserve Ltd", sector: "IT" },
  { symbol: "OBEROIHTLS", name: "EIH Associated Hotels Ltd", sector: "Hotels" },
  { symbol: "SPORTKING", name: "Sportking India Ltd", sector: "Textile" },
  { symbol: "GARWARE", name: "Garware Technical Fibres Ltd", sector: "Textile" },
  { symbol: "ALOK", name: "Alok Industries Ltd", sector: "Textile" },
  { symbol: "MAFANG", name: "Mafatlal Industries Ltd", sector: "Textile" },
  { symbol: "BOMBAY DYE", name: "Bombay Dyeing & Mfg Co Ltd", sector: "Textile" },
  { symbol: "BDISCL", name: "Bombay Dyeing & Mfg Co Ltd", sector: "Textile" },
  { symbol: "GRASIM", name: "Grasim Industries Ltd", sector: "Diversified" },
  { symbol: "ABIRLANUVO", name: "Aditya Birla Fashion and Retail Ltd", sector: "Retail" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion and Retail Ltd", sector: "Retail" },
  { symbol: "VEDANTA", name: "Vedanta Ltd", sector: "Metals" },
  { symbol: "JINDALSAW", name: "Jindal SAW Ltd", sector: "Metals" },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd", sector: "Power" },
  { symbol: "TATACHEM", name: "Tata Chemicals Ltd", sector: "Chemicals" },
  { symbol: "TATAMETALI", name: "Tata Metaliks Ltd", sector: "Metals" },
  { symbol: "NBVENTURES", name: "Nava Ltd", sector: "Diversified" },
  { symbol: "NAVABHARAT", name: "Nava Bharat Ventures Ltd", sector: "Diversified" },
  { symbol: "NOCIL", name: "NOCIL Ltd", sector: "Chemicals" },
  { symbol: "AMARкороль", name: "Amar Raja Batteries Ltd", sector: "Auto" },
  { symbol: "WINTACMED", name: "Wintac Ltd", sector: "Pharma" },
  { symbol: "GOKALDAS", name: "Gokaldas Exports Ltd", sector: "Textile" },
  { symbol: "KITEX", name: "Kitex Garments Ltd", sector: "Textile" },
  { symbol: "NITIN", name: "Nitin Spinners Ltd", sector: "Textile" },
  { symbol: "RUPA", name: "Rupa & Company Ltd", sector: "Textile" },
  { symbol: "DOLLAR", name: "Dollar Industries Ltd", sector: "Textile" },
  { symbol: "VEDL", name: "Vedanta Ltd", sector: "Metals" },
  { symbol: "ELECTCAST", name: "Electrosteel Castings Ltd", sector: "Metals" },
  { symbol: "ABMINTLLTD", name: "ABM International Ltd", sector: "Capital Goods" },
  { symbol: "EMMBI", name: "Emmbi Industries Ltd", sector: "Packaging" },
  { symbol: "ASTERDM", name: "Aster DM Healthcare Ltd", sector: "Healthcare" },
  { symbol: "HCARE", name: "Healthcare Global Enterprises Ltd", sector: "Healthcare" },
  { symbol: "NARAYANA", name: "Narayana Hrudayalaya Ltd", sector: "Healthcare" },
  { symbol: "RAINBOW", name: "Rainbow Children's Medicare Ltd", sector: "Healthcare" },
  { symbol: "SHALBY", name: "Shalby Ltd", sector: "Healthcare" },
  { symbol: "KRSNAA", name: "Krsnaa Diagnostics Ltd", sector: "Healthcare" },
  { symbol: "VIJAYA", name: "Vijaya Diagnostic Centre Ltd", sector: "Healthcare" },
  { symbol: "AGAPPE", name: "Agappe Diagnostics Ltd", sector: "Healthcare" },
  { symbol: "INDOCO", name: "Indoco Remedies Ltd", sector: "Pharma" },
  { symbol: "SUDARSCHEM", name: "Sudarshan Chemical Industries Ltd", sector: "Chemicals" },
  { symbol: "AARTI", name: "Aarti Industries Ltd", sector: "Chemicals" },
  { symbol: "SOLVAY", name: "Solvay Specialities India Pvt Ltd", sector: "Chemicals" },
  { symbol: "NEOGEN", name: "Neogen Chemicals Ltd", sector: "Chemicals" },
  { symbol: "FLUOROCHEM", name: "Gujarat Fluorochemicals Ltd", sector: "Chemicals" },
  { symbol: "GODREJIND", name: "Godrej Industries Ltd", sector: "Diversified" },
  { symbol: "GODFYPHLP", name: "Godfrey Phillips India Ltd", sector: "FMCG" },
  { symbol: "VESUVIUS", name: "Vesuvius India Ltd", sector: "Metals" },
  { symbol: "GRAPHITE", name: "Graphite India Ltd", sector: "Metals" },
  { symbol: "HEG", name: "HEG Ltd", sector: "Metals" },
  { symbol: "AIAENG", name: "AIA Engineering Ltd", sector: "Capital Goods" },
  { symbol: "KENNAMETAL", name: "Kennametal India Ltd", sector: "Capital Goods" },
  { symbol: "MMTC", name: "MMTC Ltd", sector: "Metals" },
  { symbol: "PTC", name: "PTC India Ltd", sector: "Power" },
  { symbol: "POWERMIND", name: "Power Mech Projects Ltd", sector: "Infrastructure" },
  { symbol: "SADBHAV", name: "Sadbhav Infrastructure Project Ltd", sector: "Infrastructure" },
  { symbol: "JKIL", name: "J. Kumar Infraprojects Ltd", sector: "Infrastructure" },
  { symbol: "SPML", name: "SPML Infra Ltd", sector: "Infrastructure" },
  { symbol: "HINDOILEXP", name: "Hindustan Oil Exploration Company Ltd", sector: "Energy" },
  { symbol: "SELAN", name: "Selan Exploration Technology Ltd", sector: "Energy" },
  { symbol: "SUNDRMPVT", name: "Sundaram-Clayton Ltd", sector: "Auto" },
  { symbol: "UCAL", name: "UCAL Fuel Systems Ltd", sector: "Auto" },
  { symbol: "MAHSCOOTER", name: "Maharashtra Scooters Ltd", sector: "Auto" },
  { symbol: "KINETIC", name: "Kinetic Engineering Ltd", sector: "Auto" },
  { symbol: "PVRINOX", name: "PVR INOX Ltd", sector: "Media" },
  { symbol: "INOXLEISUR", name: "INOX Leisure Ltd", sector: "Media" },
  { symbol: "GOLDIAM", name: "Goldiam International Ltd", sector: "Jewellery" },
  { symbol: "RENAISSANCE", name: "Renaissance Jewellery Ltd", sector: "Jewellery" },
  { symbol: "KDDL", name: "KDDL Ltd", sector: "Jewellery" },
  { symbol: "VAIBHAVGBL", name: "Vaibhav Global Ltd", sector: "Jewellery" },
  { symbol: "SUASTIKA", name: "Suastika Finstock Ltd", sector: "Finance" },
  { symbol: "MANINFRA", name: "Man Infraconstruction Ltd", sector: "Infrastructure" },
  { symbol: "TEXINFRA", name: "Texmaco Infrastructure & Holdings Ltd", sector: "Infrastructure" },
];
